# config.conf
# Este arquivo mapeia a organização.
# O padrão [Nome-da-Pasta]="extensão1 extensão2 ...." define a regra
# As extensões são tratadas de forma Case-Insensitive durante a organização (ex: jpg = JPG).
# Por favor, declare as extensões em letras minúsculas abaixo:

[Imagens]="jpg jpeg png gif webp bmp tiff svg cr2"
[Videos]="mp4 mkv avi mov wmv flv webm ts"
[Documentos]="pdf doc docx txt rtf odt md epub mobi azw3"
[Planilhas]="xls xlsx csv ods"
[Apresentacoes]="ppt pptx odp"
[Arquivos_Compactados]="zip rar 7z tar gz bz2 xz"
[Audio]="mp3 wav flac aac ogg m4a"
[Executaveis]="exe msi AppImage run sh bin"
[Desenvolvimento]="py js html css c cpp h java php json xml yaml sql kt go rust"
[Outros]=""
